// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyf-p1YF7CSj23nakTDTdei95KpJ7aqp8',
    appId: '1:219030110809:web:881edf4c8e04fdafa06748',
    messagingSenderId: '219030110809',
    projectId: 'fpresensi-a169c',
    authDomain: 'fpresensi-a169c.firebaseapp.com',
    storageBucket: 'fpresensi-a169c.firebasestorage.app',
    measurementId: 'G-BDX90E12WQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC03s7j4PBsQoLkysJevPdWiKyhZsretFM',
    appId: '1:357064525829:android:10fb95a54d4aee47ee346c',
    messagingSenderId: '357064525829',
    projectId: 'fpresensi',
    storageBucket: 'fpresensi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyJ0pFV6Fv75VH-suERoRb6-bWCEpq8xI',
    appId: '1:357064525829:ios:e316014d4d9b401aee346c',
    messagingSenderId: '357064525829',
    projectId: 'fpresensi',
    storageBucket: 'fpresensi.firebasestorage.app',
    iosBundleId: 'com.example.fpresensi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFlVAfrDBqtWJDzVK7e2FWzWBo8M1XltI',
    appId: '1:219030110809:ios:e2326046f54cebaea06748',
    messagingSenderId: '219030110809',
    projectId: 'fpresensi-a169c',
    storageBucket: 'fpresensi-a169c.firebasestorage.app',
    iosBundleId: 'com.example.fpresensi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyf-p1YF7CSj23nakTDTdei95KpJ7aqp8',
    appId: '1:219030110809:web:eb498b0d3b45107ca06748',
    messagingSenderId: '219030110809',
    projectId: 'fpresensi-a169c',
    authDomain: 'fpresensi-a169c.firebaseapp.com',
    storageBucket: 'fpresensi-a169c.firebasestorage.app',
    measurementId: 'G-KJ2C5V88PL',
  );

}